%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - PointCloudFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudClusterExtractor
    - ColorClusterer
    - TrayAnnotator
    - CakeAnnotator
    - CylinderAnnotator
    - KnifeAnnotator
    - ROSPublisher
